[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wompywompy"
version = "0.1.0"
description = "wompwomp"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
authors = [
    {name = "Conrad Oakes", email = "coakes@caltech.edu"},
    {name = "Joseph Rich", email = "jmrich@caltech.edu"}
]
maintainers = [
    {name = "Conrad Oakes", email = "coakes@caltech.edu"},
    {name = "Joseph Rich", email = "jmrich@caltech.edu"}
]
requires-python = ">=3.9"
keywords = ["alluvial plots", "bioinformatics", "graph theory"]
classifiers = [
    "Environment :: Console",
    "Framework :: Jupyter",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Utilities"
]
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "scipy>=1.7.0",
    "python-igraph>=0.9.0",
    "pyalluvial>=0.0.0",
    "matplotlib>=3.4.0",
    "scikit-learn>=1.0.0",
    "splitspy>=0.0.10",
    "python_tsp>=0.5.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-mpl>=0.18.0"
]

[project.urls]
"Homepage" = "https://github.com/pachterlab/wompywompy"

[tool.setuptools.packages.find]
include = ["wompywompy*"]

[tool.setuptools.package-data]
wompywompy = ["*.txt", "*.md", "*.csv"]  # Ensure additional files like data or docs are included

[project.scripts]
wompywompy = "wompywompy.main:main"  # This replaces the console_scripts entry